name: Test Deployment

on:
  push:
    branches:
      - test

jobs:
  build:
    name: Build and Upload Webpack Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
         node-version: '10.x'
      - run: npm install
      - run: npm run build --if-present

